// SRP vectors generated by pysrp (srp._pysrp with rfc5054_enable +
// no_username_in_x, SHA-256, NG_2048) — the exact configuration FindMy.py uses
// against Apple GSA. The ephemeral `a` was pinned so A/M1/K are deterministic.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { SrpClient, encryptPassword } from './srp';

const hex = (s: string) => new Uint8Array(Buffer.from(s, 'hex'));
const toHex = (b: Uint8Array) => Buffer.from(b).toString('hex');

const USERNAME = 'burner.test@icloud.com';
const PASSWORD = 'Sup3r-Secret-Pw!';
const SALT = hex('00112233445566778899aabbccddeeff');
const ITER = 1000;
const A_PRIV = hex('1a'.repeat(256));
const A_PUB =
  '8342a39377a0ef16306a15078069faf6987fc788df7ac37711c4f3ea790f8d3ed676535ea23120660bd51b0489198095890cf16e07bbb0b6c3a44595404d476f858f9824348aad8e8bee0412170aab92143def5a144d7c20230fd7de53b8d2f6e2aec88d5cfe09d30bfcfcfa93159576d5e320d0ba8a22e5ebd125221c2fecc621fc0b26d1121ef818ef6146f789af845762dad075bf50a8cc7d8f34547dacc7668f0b0041b5dad46c33e2caef424cb8a9d21dfaf48460b1c2418c7c9675e728767f36661ecbab44d2daf38fe4a110b5514a26e528a3ac83eeb6b0918837c82c4ec95b68040b6199f985b095872a14811a2be5afcb791b5575927f4af24b3538';
const B =
  '4147eae59e8ad79742bfcbad1753741d93f0ce2928ce7acb414c979296072988d7f4403df5551fb5c745d8162ec2f1abe941325eab8388c01e7c4673e4052046b8c3fba2a1e77c7c08615f47d98bf6d8ea46055d26a2fa7fca52e282baf4a4f92400e7dd20e559f2c5c08c2e15b023f9770fb6dc75c1d6fa8c8fcf3dc1873fa43bb540fe53ff6e7547b05ef032e12d3421a124c7192f9221046639aea96168ef1e5b9b2e29aada3ddc595f84a1724793146c2c4997acea952ff3d9faa1b735c76734b3d543ffe7a09e6c0701ae01f4d08676c55e54dce4534ee5dfc1e798d127fcca2b5474898a05decc74cf0cce893332e5bfabe47a46312e1554b184eb94c6';
const PK = 'a2af0f057e1d21bc1477e350b4b5829fcf45650692f0a4812a643b616b0eeca2';
const PK_S2KFO = '7f90ba9058f7e5c95ce835e5efb05b54380ad85441ecd0e898a40593afffd333';
const M1 = 'bfdf86ab7b21a2cebfa4bb13a14ef240be0c97e1a87a4d6e34bb3781f53b6451';
const K = '6dd25a5aca7e45612c9ab09b9e514498104be2e8ee75d078ed5dab591c2029b1';

test('encryptPassword matches pysrp for s2k and s2k_fo', () => {
  assert.equal(toHex(encryptPassword(PASSWORD, SALT, ITER, 's2k')), PK);
  assert.equal(toHex(encryptPassword(PASSWORD, SALT, ITER, 's2k_fo')), PK_S2KFO);
});

test('SRP A / M1 / K match pysrp', () => {
  const client = new SrpClient(USERNAME, A_PRIV);
  assert.equal(toHex(client.A), A_PUB);
  const { m1, sessionKey } = client.processChallenge(SALT, hex(B), hex(PK));
  assert.equal(toHex(m1), M1);
  assert.equal(toHex(sessionKey), K);
});
